name: Hello Workd!
on: push
jobs:
    build:
          runs-on: ubuntu-latest
          steps:
           - name: Checkout code
             uses: actions/checkout@v2
           - name: Run say hello command
             run: make say-hello                       
