name: Hello Workd!
on: push
jobs:
    build:
          runs-on: ubuntu-latest
          steps:
                - name: Run say hello command
                  run: make say-hello                       
